#!/usr/bin/env python3
"""Small exact census for the all-size-two ``n3=42`` active subcase.

Input is a graph6 catalog generated by nauty 2.9.1 with

    geng -q -td3D3 14 21:21

The standard-library checker validates every catalog entry, filters by the
mandatory 7-regular K-degree bound, and then performs an exact backtracking
search for the 2-regular positive-support graph forced by the fixed-point
identity.  It applies only common-neighbor *upper bounds* already forced among
the 21 active original points:

* at most one active common neighbor for an adjacent pair; and
* at most two active common neighbors for a nonadjacent pair.

The catalog's completeness is an external nauty-generation premise.  This
program does not independently prove nauty completeness and does not produce
a proof trace, so its zero-survivor result is a construction-lane census
pending independent verification, not a promoted theorem.
"""

from __future__ import annotations

import argparse
import hashlib
import itertools
import json
from collections import Counter
from pathlib import Path
from typing import Iterable, Sequence


ORDER = 14
POINT_COUNT = 21
EXPECTED_CATALOG_RECORDS = 112
EXPECTED_VIABLE = (
    "M???FB_w?wBOD_B_?",
    "M???FBOiAgDOD_B_?",
    "M??CEB_[@oB_B_@o?",
    "M??CE?wM@oW_P_@o?",
)


def edge(left: int, right: int) -> tuple[int, int]:
    if left == right:
        raise ValueError("loops are not edges")
    return (left, right) if left < right else (right, left)


def decode_graph6(record: str) -> tuple[int, frozenset[tuple[int, int]]]:
    """Decode the one-byte-order graph6 format used for order 14."""

    if not record or record.startswith(">>graph6<<"):
        raise ValueError("expected a bare graph6 record")
    order = ord(record[0]) - 63
    if not 0 <= order <= 62:
        raise ValueError("only the short graph6 order form is supported")
    bits: list[int] = []
    for character in record[1:]:
        value = ord(character) - 63
        if not 0 <= value <= 63:
            raise ValueError("invalid graph6 character")
        bits.extend((value >> bit) & 1 for bit in range(5, -1, -1))
    required = order * (order - 1) // 2
    if len(bits) < required:
        raise ValueError("truncated graph6 record")
    output = set()
    offset = 0
    for right in range(1, order):
        for left in range(right):
            if bits[offset]:
                output.add((left, right))
            offset += 1
    return order, frozenset(output)


def vertex_degrees(
    order: int, edges: Iterable[tuple[int, int]]
) -> tuple[int, ...]:
    values = [0] * order
    for left, right in edges:
        values[left] += 1
        values[right] += 1
    return tuple(values)


def is_triangle_free(edges: frozenset[tuple[int, int]], order: int) -> bool:
    return not any(
        all(edge(*pair) in edges for pair in itertools.combinations(triple, 2))
        for triple in itertools.combinations(range(order), 3)
    )


def mandatory_k_edges(
    point_graph: frozenset[tuple[int, int]],
) -> frozenset[tuple[int, int]]:
    """F plus every pair of F-neighbors forced by singleton crossings."""

    output = set(point_graph)
    for root in range(ORDER):
        neighbors = [
            right if left == root else left
            for left, right in point_graph
            if root in (left, right)
        ]
        if len(neighbors) != 3:
            raise AssertionError("point graph is not cubic")
        output.update(edge(left, right) for left, right in itertools.combinations(neighbors, 2))
    return frozenset(output)


def line_graph_edges(
    ordered_points: Sequence[tuple[int, int]],
) -> frozenset[tuple[int, int]]:
    return frozenset(
        (left, right)
        for left, right in itertools.combinations(range(len(ordered_points)), 2)
        if set(ordered_points[left]) & set(ordered_points[right])
    )


def support_compatibility(
    ordered_points: Sequence[tuple[int, int]],
    mandatory_k: frozenset[tuple[int, int]],
) -> tuple[tuple[int, int], ...]:
    """Largest possible support graph over every K supergraph.

    A positive support has a full 2-by-2 L crossing, so all four cross-pairs
    must be absent from K.  Testing against only mandatory K is a relaxation:
    any later K completion can only delete support opportunities.
    """

    line_edges = line_graph_edges(ordered_points)
    output = []
    for left_index, right_index in itertools.combinations(
        range(len(ordered_points)), 2
    ):
        pair = (left_index, right_index)
        if pair in line_edges:
            continue
        cross_pairs = {
            edge(left, right)
            for left in ordered_points[left_index]
            for right in ordered_points[right_index]
        }
        if not cross_pairs & mandatory_k:
            output.append(pair)
    return tuple(output)


def common_neighbor_caps_hold(
    line_edges: frozenset[tuple[int, int]],
    selected_supports: frozenset[tuple[int, int]],
    *,
    include_mu_cap: bool,
) -> bool:
    adjacency_edges = line_edges | selected_supports
    adjacency = [set() for _ in range(POINT_COUNT)]
    for left, right in adjacency_edges:
        adjacency[left].add(right)
        adjacency[right].add(left)
    for left, right in itertools.combinations(range(POINT_COUNT), 2):
        common = len(adjacency[left] & adjacency[right])
        pair = (left, right)
        if pair in adjacency_edges:
            if common > 1:
                return False
        elif include_mu_cap and common > 2:
            return False
    return True


def exact_support_factor_search(
    line_edges: frozenset[tuple[int, int]],
    compatible: Sequence[tuple[int, int]],
    *,
    include_mu_cap: bool,
    stop_after_first: bool,
) -> dict[str, object]:
    """Exact include/exclude search with degree and monotone cap propagation."""

    incident: list[list[tuple[int, int]]] = [
        [] for _ in range(POINT_COUNT)
    ]
    for pair in compatible:
        incident[pair[0]].append(pair)
        incident[pair[1]].append(pair)

    statistics = Counter()
    first_solution: tuple[tuple[int, int], ...] | None = None

    def visit(
        selected: frozenset[tuple[int, int]],
        excluded: frozenset[tuple[int, int]],
        degree: tuple[int, ...],
    ) -> None:
        nonlocal first_solution
        if stop_after_first and first_solution is not None:
            return
        statistics["nodes"] += 1
        selected_mutable = set(selected)
        excluded_mutable = set(excluded)
        degree_mutable = list(degree)

        while True:
            changed = False
            for vertex in range(POINT_COUNT):
                available = [
                    pair
                    for pair in incident[vertex]
                    if pair not in selected_mutable
                    and pair not in excluded_mutable
                ]
                need = 2 - degree_mutable[vertex]
                if need < 0 or len(available) < need:
                    statistics["degree_rejections"] += 1
                    return
                if need == 0 and available:
                    excluded_mutable.update(available)
                    changed = True
                    break
                if need == len(available) and need:
                    for pair in available:
                        left, right = pair
                        if degree_mutable[left] >= 2 or degree_mutable[right] >= 2:
                            statistics["degree_rejections"] += 1
                            return
                        selected_mutable.add(pair)
                        degree_mutable[left] += 1
                        degree_mutable[right] += 1
                        if not common_neighbor_caps_hold(
                            line_edges,
                            frozenset(selected_mutable),
                            include_mu_cap=include_mu_cap,
                        ):
                            statistics["cap_rejections"] += 1
                            return
                    changed = True
                    break
            if not changed:
                break

        if all(value == 2 for value in degree_mutable):
            statistics["solutions"] += 1
            if first_solution is None:
                first_solution = tuple(sorted(selected_mutable))
            return

        branching = []
        for vertex in range(POINT_COUNT):
            if degree_mutable[vertex] == 2:
                continue
            available = [
                pair
                for pair in incident[vertex]
                if pair not in selected_mutable
                and pair not in excluded_mutable
            ]
            need = 2 - degree_mutable[vertex]
            branching.append(
                (len(available) - need, len(available), vertex, available)
            )
        if not branching:
            statistics["degree_rejections"] += 1
            return
        _slack, _count, _vertex, available = min(branching)
        branch_pair = available[0]
        left, right = branch_pair

        if degree_mutable[left] < 2 and degree_mutable[right] < 2:
            included = frozenset((*selected_mutable, branch_pair))
            next_degree = degree_mutable[:]
            next_degree[left] += 1
            next_degree[right] += 1
            if common_neighbor_caps_hold(
                line_edges,
                included,
                include_mu_cap=include_mu_cap,
            ):
                visit(
                    included,
                    frozenset(excluded_mutable),
                    tuple(next_degree),
                )
            else:
                statistics["cap_rejections"] += 1

        visit(
            frozenset(selected_mutable),
            frozenset((*excluded_mutable, branch_pair)),
            tuple(degree_mutable),
        )

    visit(frozenset(), frozenset(), (0,) * POINT_COUNT)
    return {
        "statistics": dict(sorted(statistics.items())),
        "first_solution": (
            [list(pair) for pair in first_solution]
            if first_solution is not None
            else None
        ),
    }


def catalog_sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def run_census(path: Path) -> dict[str, object]:
    raw_lines = [
        line.strip()
        for line in path.read_text(encoding="ascii").splitlines()
        if line.strip()
    ]
    if len(raw_lines) != EXPECTED_CATALOG_RECORDS:
        raise AssertionError("unexpected graph6 catalog size")
    if len(raw_lines) != len(set(raw_lines)):
        raise AssertionError("duplicate graph6 catalog record")

    viable: list[dict[str, object]] = []
    mandatory_degree_rejections = 0
    for index, record in enumerate(raw_lines):
        order, point_graph = decode_graph6(record)
        if order != ORDER:
            raise AssertionError("catalog contains the wrong order")
        if len(point_graph) != POINT_COUNT:
            raise AssertionError("catalog graph does not have 21 edges")
        if vertex_degrees(order, point_graph) != (3,) * ORDER:
            raise AssertionError("catalog graph is not cubic")
        if not is_triangle_free(point_graph, order):
            raise AssertionError("catalog graph is not triangle-free")

        mandatory_k = mandatory_k_edges(point_graph)
        mandatory_degrees = vertex_degrees(order, mandatory_k)
        if max(mandatory_degrees) > 7:
            mandatory_degree_rejections += 1
            continue

        ordered_points = tuple(sorted(point_graph))
        line_edges = line_graph_edges(ordered_points)
        compatible = support_compatibility(ordered_points, mandatory_k)
        # The second viable representative supplies a retained diagnostic:
        # fixed-point support plus all adjacent-pair caps is consistent there,
        # but the nonadjacent mu cap kills every completion.  Running the
        # weaker search on the two 108-edge compatibility graphs is not
        # needed for the full-cap exclusion and would greatly enlarge this
        # deliberately small replay.
        lambda_search = (
            exact_support_factor_search(
                line_edges,
                compatible,
                include_mu_cap=False,
                stop_after_first=True,
            )
            if record == EXPECTED_VIABLE[1]
            else {
                "statistics": {},
                "first_solution": None,
                "status": "not_run_not_needed_for_full_cap_census",
            }
        )
        full_search = exact_support_factor_search(
            line_edges,
            compatible,
            include_mu_cap=True,
            stop_after_first=False,
        )
        viable.append(
            {
                "catalog_index": index,
                "graph6": record,
                "mandatory_k_edges": len(mandatory_k),
                "mandatory_k_degree_histogram": dict(
                    sorted(Counter(mandatory_degrees).items())
                ),
                "support_compatibility_edges": len(compatible),
                "support_compatibility_degree_histogram": dict(
                    sorted(
                        Counter(
                            sum(vertex in pair for pair in compatible)
                            for vertex in range(POINT_COUNT)
                        ).items()
                    )
                ),
                "lambda_cap_search": lambda_search,
                "lambda_mu_cap_search": full_search,
            }
        )

    if mandatory_degree_rejections != 108:
        raise AssertionError("mandatory K-degree filter changed")
    if tuple(item["graph6"] for item in viable) != EXPECTED_VIABLE:
        raise AssertionError("viable point-graph representatives changed")
    if any(
        item["lambda_mu_cap_search"]["statistics"].get("solutions", 0)
        for item in viable
    ):
        raise AssertionError("an all-size-two active support survived")

    return {
        "status": "PASS conditional all-size-two support/cap census",
        "catalog": str(path).replace("\\", "/"),
        "catalog_sha256": catalog_sha256(path),
        "catalog_records": len(raw_lines),
        "catalog_completeness_premise": (
            "nauty_2.9.1_geng_-q_-td3D3_14_21:21"
        ),
        "mandatory_degree_rejections": mandatory_degree_rejections,
        "viable_representatives": viable,
        "full_cap_survivors": 0,
        "claim_label": "CANDIDATE",
        "target_result": "UNKNOWN",
        "limitations": [
            "catalog_completeness_not_independently_proved_by_this_program",
            "no_unsat_proof_trace",
            "all_active_point_sets_restricted_to_size_2",
            "not_a_99_vertex_search",
        ],
    }


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--catalog", type=Path, required=True)
    parser.add_argument("--json", action="store_true")
    arguments = parser.parse_args(argv)
    result = run_census(arguments.catalog)
    if arguments.json:
        print(json.dumps(result, indent=2, sort_keys=True))
    else:
        print(result["status"])
        print("catalog_records", result["catalog_records"])
        print("mandatory_degree_rejections", result["mandatory_degree_rejections"])
        print("viable_representatives", len(result["viable_representatives"]))
        print("full_cap_survivors", result["full_cap_survivors"])
        print("claim_label", result["claim_label"])
        print("target_result", result["target_result"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
