"""Independent exact verifier for Wave 131.

No discovery code is imported.  The verifier rederives the subset census
and audits the sealed rational ordinary enumerator using exact Fraction and
Krawtchouk arithmetic.
"""

from __future__ import annotations

import argparse
import ctypes
import hashlib
import json
import os
from fractions import Fraction
from math import comb
from pathlib import Path


Q = Fraction
ROOT = Path(__file__).resolve().parents[2]
HERE = Path(__file__).resolve().parent
DISCOVERY = ROOT / "attempts" / "wave131-binary-lcd-enumerator"
MANIFEST_SHA256 = (
    "c305de05df2001d869db3dbfc14f7a2a8c7f305ce43471c56c66dc775e89d576"
)
N = 99
K_IMAGE = 54
K_DUAL = 45
IMAGE_SIZE = 1 << K_IMAGE
DUAL_SIZE = 1 << K_DUAL


def require(condition: bool, message: str) -> None:
    if not condition:
        raise AssertionError(message)


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for block in iter(lambda: handle.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def canonical(data: object) -> str:
    return json.dumps(data, indent=2, sort_keys=True) + "\n"


def free_memory_percent() -> float:
    if os.name != "nt":
        return 100.0

    class MemoryStatus(ctypes.Structure):
        _fields_ = [
            ("length", ctypes.c_ulong),
            ("load", ctypes.c_ulong),
            ("total_phys", ctypes.c_ulonglong),
            ("available_phys", ctypes.c_ulonglong),
            ("total_page", ctypes.c_ulonglong),
            ("available_page", ctypes.c_ulonglong),
            ("total_virtual", ctypes.c_ulonglong),
            ("available_virtual", ctypes.c_ulonglong),
            ("available_extended", ctypes.c_ulonglong),
        ]

    state = MemoryStatus()
    state.length = ctypes.sizeof(state)
    require(
        bool(ctypes.windll.kernel32.GlobalMemoryStatusEx(ctypes.byref(state))),
        "GlobalMemoryStatusEx failed",
    )
    return 100.0 * state.available_phys / state.total_phys


def preinspect() -> dict[str, object]:
    manifest = DISCOVERY / "package-manifest.sha256"
    require(sha256(manifest) == MANIFEST_SHA256, "manifest hash drift")
    entries = 0
    for line in manifest.read_text(encoding="utf-8").splitlines():
        expected, relative = line.split("  ", 1)
        require(sha256(ROOT / relative) == expected, f"sealed drift: {relative}")
        entries += 1
    require(entries == 13, "manifest entry count drift")
    return {
        "manifest_sha256": MANIFEST_SHA256,
        "entries_checked": entries,
    }


def binary_lcd_audit() -> dict[str, object]:
    # Over F2, 12I-A+2J becomes A, hence A^2=A.
    # Symmetry gives ker(A)=im(A)^perp.  Idempotence splits every x as
    # Ax+(I+A)x, with trivial intersection of image and kernel.
    return {
        "idempotent_derivation": "A^2=12I-A+2J reduces to A^2=A over F2",
        "symmetric_orthogonal_complement": "ker(A)=im(A)^perp",
        "direct_sum": "F2^99=im(A) direct_sum ker(A)",
        "image_parameters": "[99,54]",
        "kernel_parameters": "[99,45]",
        "both_LCD": True,
        "image_even_reason": "generated by the 99 even-weight adjacency rows",
        "image_restricted_dot_product": "nondegenerate alternating",
        "image_symplectic_dimension": 54,
        "all_one_in_kernel_reason": "A one = 14 one = 0 over F2",
        "dual_complement_symmetry": "B_w=B_(99-w)",
        "subset_map_injectivity": {
            "domain": "|S|<=3",
            "image_map": (
                "A1_S=A1_T puts 1_(S symmetric_difference T) in ker(A) "
                "at weight <=6, contradicting d(ker A)>=8 unless S=T"
            ),
            "dual_map": (
                "(I+A)1_S=(I+A)1_T puts the difference in im(A) at "
                "weight <=6, contradicting d(im A)>=8 unless S=T"
            ),
            "both_injective": True,
        },
    }


def subset_distribution_audit() -> dict[str, object]:
    vertices = N
    degree = 14
    edges = vertices * degree // 2
    pairs = comb(vertices, 2)
    nonedges = pairs - edges
    triangles = edges // 3

    # N(v)=7K2, so a centered induced path chooses two neighbors from
    # different matched pairs.
    paths = vertices * (comb(degree, 2) - 7)

    # An edge has 72 third vertices adjacent to neither endpoint.
    # Twelve of those meet the unique common neighbor of the edge.
    one_edge_c1 = edges * 12
    one_edge_c0 = edges * 60

    independent_total = (
        comb(vertices, 3)
        - triangles
        - paths
        - one_edge_c1
        - one_edge_c0
    )
    # An independent triple with a common neighbor selects one endpoint from
    # each of three different K2 components inside its 7K2 neighborhood.
    independent_c1 = vertices * comb(7, 3) * 8
    independent_c0 = independent_total - independent_c1
    require(
        (
            edges,
            nonedges,
            triangles,
            paths,
            one_edge_c0,
            one_edge_c1,
            independent_c0,
            independent_c1,
        )
        == (693, 4158, 231, 8316, 41580, 8316, 70686, 27720),
        "subset census drift",
    )
    require(
        independent_total + one_edge_c0 + one_edge_c1 + paths + triangles
        == comb(99, 3),
        "three-subset partition drift",
    )

    rows = [
        {
            "type": "empty",
            "count": 1,
            "edges": 0,
            "common_all_three": 0,
            "image_weight": 0,
            "dual_weight": 0,
        },
        {
            "type": "vertex",
            "count": vertices,
            "edges": 0,
            "common_all_three": 0,
            "image_weight": 14,
            "dual_weight": 15,
        },
        {
            "type": "edge",
            "count": edges,
            "edges": 1,
            "common_all_three": 0,
            "image_weight": 26,
            "dual_weight": 24,
        },
        {
            "type": "nonedge",
            "count": nonedges,
            "edges": 0,
            "common_all_three": 0,
            "image_weight": 24,
            "dual_weight": 26,
        },
        {
            "type": "independent_c0",
            "count": independent_c0,
            "edges": 0,
            "common_all_three": 0,
            "image_weight": 30,
            "dual_weight": 33,
        },
        {
            "type": "independent_c1",
            "count": independent_c1,
            "edges": 0,
            "common_all_three": 1,
            "image_weight": 34,
            "dual_weight": 37,
        },
        {
            "type": "one_edge_c0",
            "count": one_edge_c0,
            "edges": 1,
            "common_all_three": 0,
            "image_weight": 32,
            "dual_weight": 31,
        },
        {
            "type": "one_edge_c1",
            "count": one_edge_c1,
            "edges": 1,
            "common_all_three": 1,
            "image_weight": 36,
            "dual_weight": 35,
        },
        {
            "type": "induced_path",
            "count": paths,
            "edges": 2,
            "common_all_three": 0,
            "image_weight": 34,
            "dual_weight": 33,
        },
        {
            "type": "triangle",
            "count": triangles,
            "edges": 3,
            "common_all_three": 0,
            "image_weight": 36,
            "dual_weight": 39,
        },
    ]

    image: dict[int, int] = {}
    dual: dict[int, int] = {}
    for row in rows[1:]:
        image[row["image_weight"]] = image.get(row["image_weight"], 0) + row["count"]
        dual[row["dual_weight"]] = dual.get(row["dual_weight"], 0) + row["count"]
    expected_image = {
        14: 99,
        24: 4158,
        26: 693,
        30: 70686,
        32: 41580,
        34: 36036,
        36: 8547,
    }
    expected_dual = {
        15: 99,
        24: 693,
        26: 4158,
        31: 41580,
        33: 79002,
        35: 8316,
        37: 27720,
        39: 231,
    }
    require(image == expected_image, "image distribution drift")
    require(dual == expected_dual, "dual distribution drift")

    # Recheck the three-set weight formula and the endpoint toggle for every
    # row rather than accepting the tabulated weights.
    for row in rows[4:]:
        expected_f = (
            30 + 2 * row["edges"] + 4 * row["common_all_three"]
        )
        require(row["image_weight"] == expected_f, "three-set f-weight drift")
        odd_induced_degrees = (
            0 if row["type"].startswith("independent") or row["type"] == "triangle"
            else 2
        )
        expected_g = expected_f + 3 - 2 * odd_induced_degrees
        require(row["dual_weight"] == expected_g, "three-set g-weight drift")

    complement = {N - weight: count for weight, count in dual.items()}
    return {
        "rows_for_all_subset_types_size_at_most_3": rows,
        "three_set_total": comb(99, 3),
        "image_forced_lower": {str(k): v for k, v in image.items()},
        "dual_forced_lower": {str(k): v for k, v in dual.items()},
        "dual_complement_forced_lower": {
            str(k): v for k, v in sorted(complement.items())
        },
        "three_set_weight_formula": "wt(A1_S)=30+2e+4c",
    }


def krawtchouk(degree: int, weight: int) -> int:
    low = max(0, degree - (N - weight))
    high = min(degree, weight)
    return sum(
        (-1) ** intersection
        * comb(weight, intersection)
        * comb(N - weight, degree - intersection)
        for intersection in range(low, high + 1)
    )


def load_enumerator(payload: dict[str, object], key: str) -> list[Q]:
    coefficients = [Q(0)] * (N + 1)
    for weight, value in payload[key].items():
        coefficients[int(weight)] = Q(value)
    return coefficients


def witness_audit(distributions: dict[str, object]) -> dict[str, object]:
    path = DISCOVERY / "rational-witness.json"
    payload = json.loads(path.read_text(encoding="utf-8"))
    image = load_enumerator(payload, "image_coefficients")
    dual = load_enumerator(payload, "dual_coefficients")

    require(len(image) == len(dual) == 100, "enumerator length drift")
    require(all(value >= 0 for value in image + dual), "negative coefficient")
    require(image[0] == dual[0] == dual[99] == 1, "constant/all-one drift")
    require(sum(image) == IMAGE_SIZE, "image order drift")
    require(sum(dual) == DUAL_SIZE, "dual order drift")
    require(all(image[w] == 0 for w in range(1, 14)), "image distance drift")
    require(all(dual[w] == 0 for w in range(1, 15)), "dual distance drift")
    require(all(image[w] == 0 for w in range(1, 100, 2)), "image parity drift")
    require(all(dual[w] == dual[99 - w] for w in range(100)),
            "dual complement symmetry drift")

    bound_checks = 0
    for table_name, coefficients in (
        ("image_forced_lower", image),
        ("dual_forced_lower", dual),
        ("dual_complement_forced_lower", dual),
    ):
        for weight, bound in distributions[table_name].items():
            require(coefficients[int(weight)] >= bound, f"forced bound drift: {table_name}")
            bound_checks += 1

    forward_failures: list[int] = []
    inverse_failures: list[int] = []
    forward_values: list[Q] = []
    inverse_values: list[Q] = []
    for degree in range(100):
        transformed = sum(
            image[weight] * krawtchouk(degree, weight)
            for weight in range(100)
        ) / IMAGE_SIZE
        forward_values.append(transformed)
        if transformed != dual[degree]:
            forward_failures.append(degree)
    for degree in range(100):
        transformed = sum(
            dual[weight] * krawtchouk(degree, weight)
            for weight in range(100)
        ) / DUAL_SIZE
        inverse_values.append(transformed)
        if transformed != image[degree]:
            inverse_failures.append(degree)
    require(not forward_failures and not inverse_failures, "MacWilliams row drift")

    image_fractional = [
        weight for weight, value in enumerate(image) if value.denominator != 1
    ]
    dual_fractional = [
        weight for weight, value in enumerate(dual) if value.denominator != 1
    ]
    require(len(image_fractional) == 34, "image fractional count drift")
    require(len(dual_fractional) == 32, "dual fractional count drift")
    image_minimum = min(w for w, value in enumerate(image) if w and value)
    dual_minimum = min(w for w, value in enumerate(dual) if w and value)
    require((image_minimum, dual_minimum) == (14, 15), "formal distance drift")

    # Degree zero MacWilliams rows are the two order identities.
    require(forward_values[0] == 1 and inverse_values[0] == 1,
            "degree-zero MacWilliams normalization drift")
    return {
        "witness_sha256": sha256(path),
        "coefficients_checked": 200,
        "all_coefficients_nonnegative": True,
        "image_order": str(IMAGE_SIZE),
        "dual_order": str(DUAL_SIZE),
        "image_minimum_nonzero_weight": image_minimum,
        "dual_minimum_nonzero_weight": dual_minimum,
        "image_even": True,
        "dual_complement_symmetric": True,
        "forced_lower_bound_checks": bound_checks,
        "forward_MacWilliams_rows_checked": 100,
        "inverse_MacWilliams_rows_checked": 100,
        "forward_failures": forward_failures,
        "inverse_failures": inverse_failures,
        "image_fractional_coefficient_count": len(image_fractional),
        "dual_fractional_coefficient_count": len(dual_fractional),
        "image_fractional_weights": image_fractional,
        "dual_fractional_weights": dual_fractional,
        "formal_integral_enumerator": False,
        "realized_binary_code": False,
    }


def integral_scout_audit() -> dict[str, object]:
    path = DISCOVERY / "integral-scout.json"
    payload = json.loads(path.read_text(encoding="utf-8"))
    require(payload["claim_label"] == "UNKNOWN", "integral scout label drift")
    require(
        payload["result"]["status"] == "UNKNOWN_HARD_TIMEOUT",
        "integral scout status drift",
    )
    require(not payload["negative_inference_allowed"], "timeout status inflation")
    require(payload["hard_wall_seconds"] == 15, "hard wall drift")
    return {
        "sealed_scout_sha256": sha256(path),
        "classification": "UNKNOWN",
        "status": "UNKNOWN_HARD_TIMEOUT",
        "integral_solution_certificate_present": False,
        "infeasibility_certificate_present": False,
        "negative_inference_allowed": False,
        "verifier_interpretation": (
            "The bounded timeout establishes neither integral feasibility "
            "nor infeasibility."
        ),
    }


def build_results() -> dict[str, object]:
    require(free_memory_percent() >= 15.0, "memory floor before verifier")
    seal = preinspect()
    lcd = binary_lcd_audit()
    distributions = subset_distribution_audit()
    witness = witness_audit(distributions)
    scout = integral_scout_audit()
    require(free_memory_percent() >= 15.0, "memory floor after verifier")
    return {
        "format": "wave131-independent-verification-v1",
        "claim_label": "VERIFIED",
        "scope": (
            "Conditional binary LCD identities, all subset distributions "
            "through size three, and exact rational ordinary MacWilliams "
            "feasibility only."
        ),
        "preinspection": seal,
        "binary_lcd": lcd,
        "forced_distributions": distributions,
        "rational_witness": witness,
        "integral_scout": scout,
        "comparison": {
            "discovery_claims_matched": True,
            "corrections": [],
            "clarifications": [
                (
                    "The rational formal enumerator does not certify "
                    "integrality, LCD, or existence of a code."
                ),
                (
                    "An integral formal enumerator would still not realize "
                    "the 99 distinguished rows or the graph."
                ),
            ],
        },
        "status_wall": {
            "integral_formal_enumerator": "UNKNOWN",
            "binary_code_constructed": False,
            "adjacency_matrix_constructed": False,
            "graph_constructed": False,
            "rank_excluded": False,
            "Conway_99": "UNKNOWN",
            "literature_novelty": "UNKNOWN",
        },
        "memory": {"floor_percent": 15, "floor_respected": True},
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path)
    parser.add_argument("--verify", type=Path)
    args = parser.parse_args()
    rendered = canonical(build_results())
    if args.verify:
        require(args.verify.read_text(encoding="utf-8") == rendered,
                "independent result drift")
    if args.output:
        args.output.write_text(rendered, encoding="utf-8", newline="\n")
    if not args.output and not args.verify:
        print(rendered, end="")


if __name__ == "__main__":
    main()
